config/routes.rb
Telemed::Application.routes.draw do
  resources :users

  root 'static_pages#home'

  match '/signup', to: 'users#new', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/login', to: 'static_pages#login', via: 'get'

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		#@user.save
  	else
  		render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telemed | <%= yield(:title) %></title>
  <link href='http://fonts.googleapis.com/css?family=Krona+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!--header and footer-->
<div id="header">
	<div id="logo", onclick="location.href='http://www.gmail.com';" style="cursor:pointer;"> Telemed </div>
	<div class="items">
		<%= link_to root_path, id:"item" do %> Home <% end %>
		<%= link_to about_path, id:"item" do %> About <% end %>
		<%= link_to login_path, id:"item" do %> Log In <% end %>
	</div>
</div>

<div id="footer">
	<%= debug(params) if Rails.env.development? %>
</div> 

<!-- body -->

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<br>
<br>
<h1>Home</h1>
<p>
	You can sign up here:
	<%= link_to 'Sign Up Here', signup_path =%>
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<br> <br>
<%= form_for(@user) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation, "Confirmation" %>
	<%= f.password_field :password_confirmation %>

	<%= f.submit "Create my Account" %>
<% end %>

app/views/users/show.html.erb
<br> <br>
<%= @user.name %>, <%= @user.email %>